[package]
name = "example_project"
version = "0.1.0"
edition = "2021"

[dependencies]
example_library_backend = { path = "../example_library_backend" }
example_library_macro = { path = "../example_library_macro" }
