[package]
name = "macro_parser"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
parser = { path = "../parser" }
nom = "7.1.0"
quote = "1.0.14"
syn = { version = "1.0.85", features = ["full", "extra-traits"] }
