[package]
name = "nom_macro"
version = "0.1.0"
edition = "2021"

[dependencies]
quote = "1.0.14"
syn = { version = "1.0.85", features = ["full"] }
parser = { path = "./parser" }
macro_parser = { path = "./macro_parser" }

[workspace]
members = ["parser", "macro_parser"]

